### ISSUE TITLE
Images miss SCS metadata

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/cluster-stack-provider-openstack#223]
/kind bug

The CSPO registers missing node images which is nice.
However, these node images do not carry the metadata that we want *all* (public) images to have on SCS environments.
(We can ignore the naming RECOMMENDATION, but not the required properties, IMVHO.)

See [SCS-v0102](https://docs.scs.community/standards/iaas/scs-0102) for the wanted metadata.
We should have something like:
architecture='x86_64'
hw_disk_bus='scsi', hw_rng_model='virtio', hw_scsi_model='virtio-scsi'
hypervisor_type='qemu'
image_build_date='20XX-YY-ZZ'
image_description='Ubuntu 22.04 node image for capo'
image_original_user='ubuntu'
image_source='https://minio.services.osism.tech/openstack-k8s-capi-images/ .....' (please insert correct location!)
provided_until='20AA-BB-CC' (should be build date plus 14m)
replace_frequency='never'
uuid_validity='20AA-BB-CC'

The `hw_disk_bus` settings are merely a recommendation, but they will help @Nils98Ar ...

**Comment by jschoone** [comment]
Right, the properties are missing in the [CRD](https://doc.crds.dev/github.com/SovereignCloudStack/cluster-stack-provider-openstack/infrastructure.clusterstack.x-k8s.io/OpenStackNodeImageRelease/v1alpha1@v0.1.0-alpha.2#spec-image-createOpts). Should be added as a map to make it possible to add them to the node image config like this:
```yaml
  createOpts:
    container_format: bare
    disk_format: qcow2
    name: ubuntu-capi-image-v1.29.12
    visibility: private
    properties:
      hw_disk_bus: "scsi"
      hw_rng_model: "virtio"
      hw_scsi_model: "virtio-scsi"
```
