### ISSUE TITLE
Enable Support for multiple OpenStack clouds in OpenStackClusterStackReleaseTemplate

### ISSUE THREAD

**Issue by matofeder** [SovereignCloudStack/cluster-stack-provider-openstack#85]
/kind proposal

#### User Story

As a user, I aim to deploy multiple Kubernetes clusters across various OpenStack clouds or projects. My goal is to reuse a single cluster stack definition for this purpose. 
It means I want to spawn **N** Kubernetes clusters in **M** environments utilizing **1** cluster stack that is deployed in a dedicated Kubernetes namespace.

####  Current State

Currently, OpenStack access is defined via clouds.yaml, stored in the secret and referenced in the OpenStackClusterStackReleaseTemplate as follows:

```yaml
spec:
  cloudName: <cloud name>
  identityRef:
    kind: Secret
    name: <secret name>
```
This approach binds the cluster stack to only one OpenStack project, resulting in the following issues: 

Images referenced in the cluster stack will be uploaded only to the OpenStack project defined by the `<cloud name>` above. 
Consequently, if an end-user intends to reuse one cluster stack for multiple Kubernetes clusters, they are limited to utilizing the OpenStack project defined by the `<cloud name>` above, as only that OpenStack project contains the required images defined by the cluster stack.
If an end-user wants to utilize multiple OpenStack clouds or projects, they have to have multiple copies of the same cluster stack. It means, If I want to spawn **N** Kubernetes clusters in **M** environments, I have to utilize **M** cluster stacks.

#### Proposal

OpenStack access is defined via clouds.yaml, stored in the secret and referenced in the OpenStackClusterStackReleaseTemplate as follows:

```yaml
spec:
  cloudNames: 
  - <cloud name A>
  - <cloud name B>
  - ...
  identityRef:
    kind: Secret
    name: <secret name>
```

Images referenced in the cluster stack will be uploaded to all OpenStack clouds/projects defined by the `cloudNames` list. Then CSPO ensures that the required images will be uploaded to all OpenStack clouds/projects defined by the cloudNames list. 
This allows an end-user to utilize multiple OpenStack clouds or projects using a single cluster stack.
